### ISSUE TITLE
MouseDown and DragMove event calls conflict

### ISSUE THREAD

**Issue by Yangshiyu2012** [tainicom/TreeViewEx#5]
The software window calls the MouseLeftButtonDown event to implement the "DragMove()" window drag event and references the TreeViewEx library. When the mouse clicks to select a node, the Call("OnMouseDown", e) event in the code does not execute properly. Only when the window is maximized can it be normal;

**Comment by nkast** [comment]
If I understand it correctly, in your software you are subscribing
to the TreeViewEx .MouseLeftButtonDown event to implement 
your own custom Drag system, which sets Handled=true and 
disables the build in handler of MouseDown. 

It's not good idea to handle events and hide them from the control.

The control already has the DragCommand and DropCommand.
You should prefer using those instead of doing your own implementation.
Please look at the  DragNDropSample.
https://github.com/tainicom/TreeViewEx/tree/master/Samples/DragNDropSample/.
  
As for the issue with the maximized window, I have to assume that's also 
some implementation detail of your software.

**Comment by Yangshiyu2012** [comment]
Thank you very much for your reply.
I'm sorry if I didn't express the question exactly last time,This program's event conflict has been resolved outside the reference, see if there is a more optimal solution;
The real scenario is: I created a WPF window, and then referenced the TreeViewEx control under this window, because the window has no border mode [WindowStyle="None"], So for this window I implemented the free drag event [this.mouseleftButtonDown +=(S, E)=>{this.dragmove ();}], when the window is normally displayed [WindowState="Normal"]; The TreeViewEx control referenced in this window cannot trigger the event of selecting a node. The main reason is that [Call("OnMouseDown", e)] in the TreeViewEx code conflicts with [MouseLeftButtonDown] in the parent window.

The current solution is that I changed the parent window's free drag event;
